/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Principle;

import Util.ConnectDatabase;
import java.util.ArrayList;
import org.jfree.chart.ChartColor;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.Plot;
import org.jfree.data.general.DefaultPieDataset;
import org.opencv.core.Core;

/**
 *
 * @author liko97
 */
public class FReport extends javax.swing.JFrame {
    ConnectDatabase connectdb = new ConnectDatabase();
    static String stDate=""; //start date of searching
    static String enDate=""; // end date of searching
    int ct;
    ArrayList programD = new ArrayList();
    /** Creates new form FReport */
    public FReport(String startDate, String endDate) {
        this.stDate=startDate;
        this.enDate=endDate;
        initComponents();
        
        //draw the chart for visit frequency in a time slot group by gender
        JFreeChart chart = ChartFactory.createPieChart("Frequency", initJframe("male",startDate,endDate),
				true, true, false);
        ChartPanel cpp = new ChartPanel(chart);
                cpp.setBounds(20, 20, 250, 220);	
                jPanel1.add(cpp);
                jPanel1.setVisible(true);
                cpp.setVisible(true);
        JFreeChart chart1 = ChartFactory.createPieChart("Frequency", initJframe("female",startDate,endDate),
				true, true, false);
        ChartPanel cpp1 = new ChartPanel(chart1);
                cpp1.setBounds(20, 20, 250, 230);	
                jPanel2.add(cpp1);
                jPanel2.setVisible(true);
                cpp1.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visit Frequency Report");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 280, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 289));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel1.setText("Male");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        jLabel2.setText("Female");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        setSize(new java.awt.Dimension(600, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * click "back" button to return to menu
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private DefaultPieDataset initJframe(String gender,String sd, String ed){
        try {
            //get how many programs the visited students are from between starttime and endtime
            String SQL = "SELECT COUNT(DISTINCT Program) FROM VisitRecord where Visit_Time BETWEEN STR_TO_DATE('"+sd+"','%Y-%m-%d') AND STR_TO_DATE('"+ed+"','%Y-%m-%d')";
            connectdb.connect();
            connectdb.executeSQL(SQL);
            connectdb.rs.next();
            String cts=connectdb.rs.getString(1);
            ct=Integer.parseInt(cts);
           
        } catch (Exception e) {
            System.out.println("count Error: " + e);
        }
        try {
            //get which programs the visited students are from between starttime and endtime
            String SQLA = "SELECT DISTINCT Program FROM VisitRecord where Visit_Time BETWEEN STR_TO_DATE('"+sd+"','%Y-%m-%d') AND STR_TO_DATE('"+ed+"','%Y-%m-%d')";
            connectdb.connect();
            connectdb.executeSQL(SQLA);
            connectdb.rs.next();
            programD.add(connectdb.rs.getString(1));
            while(connectdb.rs.next()){
                programD.add(connectdb.rs.getString(1));
            }
            
        } catch (Exception e) {
            System.out.println("arraylist Error: " + e);
        }
        connectdb.disconnect();
        DefaultPieDataset dataset = new DefaultPieDataset();
        for(int i = 0; i < ct; i++){
            try {
                //get how many records are from program x and gender y between starttime and endtime    
                String SQL = "SELECT COUNT(*) FROM VisitRecord WHERE Program="+"'"+String.valueOf(programD.get(i))+"'"+"and gender="+"'"+gender+"'"+"and Visit_Time BETWEEN STR_TO_DATE('"+sd+"','%Y-%m-%d') AND STR_TO_DATE('"+ed+"','%Y-%m-%d')";
                connectdb.connect();
                connectdb.executeSQL(SQL);
                connectdb.rs.next();
                String ps=connectdb.rs.getString(1);
                int tempp=Integer.parseInt(ps);
                dataset.setValue(String.valueOf(programD.get(i)), tempp);
            } catch (Exception e) {
            System.out.println("get Error: " + e);
            }
        }
        return dataset;
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
