/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principle;

import Util.ConnectDatabase;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import org.opencv.core.Core;
import java.text.SimpleDateFormat;

/**
 * The class used to add visit reasons for every student drops by 
 * @author liko97
 */
public class VisitReason extends javax.swing.JFrame {
    ConnectDatabase connectdb = new ConnectDatabase();
    private int id;
    private String fname;
    private String lname;
    private String program;
    private String gender;
    private String[] choiceList = new String[]{"ask stapler", "tuition fees", "complaints","collect assignments", "meet Nereshnee", "meet Lourdes", "other"};
    private String choiceSelected;
    /**
     * The constructor of the class
     * Creates new form VisitReason
     */
    public VisitReason() {
        initComponents();
        addCom();
    }
    
    /**
     * The constructor with parameters to receive data from upstream classes
     * @param id
     * @param fname
     * @param lname
     * @param program
     */
    public VisitReason(int id,String fname,String lname,String program, String gender){
        this.id=id;
        this.fname=fname;
        this.lname=lname;
        this.program=program;
        this.gender=gender;
        initComponents();
        addCom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visit Reason");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Please Enter the Detailed Reason:");

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jComboBox1.setMinimumSize(new java.awt.Dimension(54, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(54, 40));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setText("Select Visit Reason: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(90, 90, 90))
        );

        setSize(new java.awt.Dimension(600, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * The method used to set action when button 1 is clicked
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // To get the choiced item from the combobox 
        String selected=choiceSelected;
        String inputReason="";
        // To examine if "others" item is selected. If does, get imput from textfield
        if(choiceSelected.equals("others")){
            inputReason =jTextField1.getText();
        }else{
            inputReason =selected;
        }
        SimpleDateFormat sdf = new SimpleDateFormat();// Standardlize the date 
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss");  
        Date date = new Date();
        String dates=sdf.format(date);
         try{
            connectdb.connect();
            // use preparedStatement to preset data that needed to be saved in database
            PreparedStatement psql;  
            psql = connectdb.conn.prepareStatement("INSERT INTO  VisitRecord(id,First_Name,Last_Name,Program,Visit_Time,Visit_Reason,gender)"+"VALUES(?,?,?,?,?,?,?)");
		//set data for different column
                psql.setInt(1, id);  
		psql.setString(2, fname);
		psql.setString(3, lname);
		psql.setString(4,program);
                psql.setString(5, dates);
                psql.setString(6,inputReason);
                psql.setString(7,gender);
                //Insert into database when preset is done
		psql.executeUpdate();  
		psql.close();
                jLabel1.setText("Saving successed");
                System.loadLibrary(Core.NATIVE_LIBRARY_NAME );
                // input window function
                Toolkit toolkit = getToolkit();
                // get the size of screen
                Dimension screenSize = toolkit.getScreenSize();
                // set new size of the screen to fit the need of dashboard
                int width = (635);
                int height = (796) ;
                setSize(width, height);
                // call for dashboard class
                new Dashboard(id).setVisible(true);
                this.setVisible(false);   
		}catch(SQLException ex){
                     for(Throwable e : ex ) {
    System.out.println("Error encountered: " + e);
  }
                    jLabel1.setText("Saving SQL failed, please retry");
		}catch (Exception e) {
                    System.out.println("Error encountered: " + e);
                    jLabel1.setText("Saving NonSQL failed, please retry");
		}finally{
				
		}
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED)
                {
                    choiceSelected=(String) jComboBox1.getSelectedItem();
                }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

        private void addCom(){
        for(int i=0;i<choiceList.length;i++){
            jComboBox1.addItem(choiceList[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
